server:
  port: 8100
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      foo-bar:
        max-attempts: 5
        wait-duration: 1s
spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: book_service
    user: root
    password: root
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
