spring:
  application:
    name: greeting-service
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      profile: prod
greeting-service:
  greeting: "Olá"
  default-value: "Mundo"
management:
  endpoints:
    web:
      exposure:
        include: "*"
